version: '3'
services:
  planner:
    image: atulbipin/ezplanner-planner-service:master-23ac4db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '5000:5000'
    networks:
      - webnet

  pdf-parser:
    image: atulbipin/ezplanner-pdf-parser-service:1.0.1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '5001:8080'
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  nginx:
    image: atulbipin/ezplanner-api-gateway:master-79bace4
    ports:
      - '80:80'
      - '443:443'
    networks:
      - webnet
    depends_on:
      - planner
      - visualizer

networks:
  webnet:
