version: '3'
services:
  planner:
    image: atulbipin/ezplanner-planner:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - '5000:5000'
    networks:
      - webnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  nginx:
    image: atulbipin/ezplanner-api-gateway:1.0 
    ports:
      - '80:80'
    networks:
      - webnet
    depends_on:
      - planner

networks:
  webnet:
